---
# tasks file for ansible-docker-rocketchat

- name: "Configurer le parefeu (ufw)"
  include: configurer_parefeu.yml

- name: "configurer et activer le vhost pour nginx (avec SSL)"
  block:
    - name: "configurer le vhost pour nginx"
      template:
        src: "vhost.j2"
        dest: "/etc/nginx/sites-available/{{ hote }}"
        mode: 0644
        owner: root
    - name: "(Re)générer le certificat Let's Encrypt avec Certbot"
      command: "certbot --nginx --non-interactive --agree-tos --domains {{ hote }} -m mathieugpilote@coderbunker.com"
    - name: "activer le vhost pour nginx"
      file:
        src: "/etc/nginx/sites-available/{{ hote }}"
        dest: "/etc/nginx/sites-enabled/{{ hote }}"
        state: link
    - name: "redémarrer nginx"
      service:
        name: nginx
        state: restarted
  become: yes

- name: "Ajouter l'utilisateur Unix qui exécutera docker/docker-compose"
  user:
    name: "{{ utilisateur_unix }}"
    groups: docker
    append: yes
  become: yes

- name: "Cloner le dépôt git du projet docker-compose pour Rocket Chat"
  git:
    repo: "{{ depot_git_distant }}"
    dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}"
  become: yes
  become_user: "{{ utilisateur_unix }}"
   
- name: "Configurer le fichier .env du projet Docker Composer de Rocket Chat"
  template:
    src: "env.j2"
    dest: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}/.env"
    owner: "{{ utilisateur_unix }}"
    group: "{{ utilisateur_unix }}"
    mode: 0644
  become: yes

# À FAIRE : convertir en handler / redémarrer uniquement si .env a changé
- name: "Redémarrer les services via docker-compose (sans rebâtir)"
  docker_compose:
    project_src: "/home/{{ utilisateur_unix }}/{{ depot_git_local }}"
    state: present
    restarted: yes
  become: yes
  become_user: "{{ utilisateur_unix }}"
